site_name: I. Assis
site_url: https://i-assis.github.io/home/
site_author: I. Assis (israel.dynamics[]gmail.com)
site_description: Dynamic systems, learning theory.
copyright: Dynamic systems, learning theory.

# Repository
repo_name: i-assis/home
repo_url: https://github.com/i-assis/home/
edit_uri: ""

# https://docs.github.com/en/pages
# For root URLs (like http://example.com/) you must provide an index.html file.
# nav:
#   - CV: '/docs/cv'


theme:
  # https://squidfunk.github.io/mkdocs-material/creating-your-site/#configuration
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  logo: _assets/images/8cell.png
  extra:
    homepage: https://i-assis.github.io/home/
  favicon: _assets/images/8cell.png
  features:
    - navigation.instant
    # - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    # - navigation.expand # all folders are expanded
    - navigation.indexes # link an index page to its parent folder
    - navigation.top # show the back-to-top button
    # - toc.follow
    # - toc.integrate # show the table of contents in the navigation pane    
    # Search
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search
    - search.suggest # display the likeliest completion for the last word
    - search.highlight # highlight all occurrences
    - search.share # show a share button of the current search
    # Content
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - content.code.annotate # add comment to code blocks
    - content.tabs.link # link tabs with the same label

#   consent:
#     title: Cookie consent
#     description: >-
#       We use cookies to recognize your repeated visits and preferences, as well
#       as to measure the effectiveness of our documentation and whether users
#       find what they're searching for. With your consent, you're helping us to
#       make our documentation better.

plugins:
  - search:
      lang:
        - en
      separator: '[\s\-\.]'  
  - awesome-pages # pip install mkdocs-awesome-pages-plugin
  - tags
  - git-revision-date-localized: # pip3 install mkdocs-git-revision-date-localized-plugin
      enable_creation_date: true
      fallback_to_build_date: true
      type: iso_date
  - encryptcontent: # pip install mkdocs-encryptcontent-plugin
      hljs: false
      arithmatex: false
      mermaid2: false
      password_button: true
      remember_password: true
      reload_scripts:
      - "./_assets/extra.js"
  - exclude: # pip3 install mkdocs-exclude
      glob:
        - "*/exclude/*"
      regex:
        - '.*\[exclude\].*'
  # - blog: # [FOR MKDOCS SPONSORS ONLY]
  #     post_date_format: full
  #     blog_dir: /blog/
  # - social:
  #     cards_font: Roboto
  #     cards_color:
  #       fill: "#0FF1CE"
  #       text: "#FFFFFF"

#   - privacy # [FOR MKDOCS SPONSORS ONLY]

# [CACHE NOT YET WORKING]
# name: ci
#   on:
#     push:
#       branches:
#         - master
#         - main
#   jobs:
#     deploy:
#       runs-on: ubuntu-latest
#       steps:
#         - uses: actions/checkout@v2
#         - uses: actions/setup-python@v2
#           with:
#             python-version: 3.x
#         - uses: actions/cache@v2
#           with:
#             key: ${{ github.ref }}
#             path: .cache
#         - run: pip install mkdocs-material
#         - run: mkdocs gh-deploy --force

# Extensions
markdown_extensions:
  #
  # Python Markdown
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  #
  - abbr # add a small tooltip to elements
  - admonition # add call-out blocks
  - attr_list # allow to add HTML attributes and CSS classes
  - def_list # add description lists
  - footnotes # define inline footnotes
  - meta # attach arbitrary key-value pairs to a document
  - md_in_html # allow to write Markdown inside HTML elements
  - tables # create tables in Markdown
  - toc: # generate a table of contents from documents
      permalink: true # anchor
      toc_depth: 4 # header 1 to header 4
  - sane_lists # make better lists
  - smarty: # convert some special characters
      smart_angled_quotes: true
  - mdx_math # pip install --upgrade python-markdown-math
  #
  # Python Markdown Extensions
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/
  #
  - pymdownx.arithmatex: # render math equations
      generic: true
  - pymdownx.betterem: # improve the detection of Markup to emphasize text in Markdown
      smart_enable: all
  - pymdownx.caret # define superscript
  - pymdownx.mark # highlight text
  - pymdownx.tilde # define subscript
  - pymdownx.critic # track changes
  - pymdownx.details # add collapsible call-outs
  - pymdownx.emoji: # add inlines bundled and custom icons and emojis 
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight # highlight code blocks
      # linenums_style: pymdownx-inline
      # anchor_linenums: true # create anchor link on each line of code
  - pymdownx.inlinehilite # highlight inline code blocks  
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde
  - pymdownx.snippets: #  embed content from arbitrary files into a document
      check_paths: true
  - pymdownx.tabbed: # group related content and code blocks under accessible tabs
      alternate_style: true
  - pymdownx.tasklist: # define list of task with checkbox
      custom_checkbox: true
  - pymdownx.escapeall:
      hardbreak: true # use \ to create new line
      nbsp: true # use \<space> to create &nbsp;
  - pymdownx.progressbar
  - pymdownx.keys # syntax ++ctrl+c++ does not look clear in MD document

# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve by sending an e-mail.
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer
  social:   
    - icon: fontawesome/brands/google
      link: https://scholar.google.com/citations?hl=en&user=GPu9jbIAAAAJ
    - icon: fontawesome/brands/scribd
      link: https://www.scopus.com/authid/detail.uri?authorId=57215007400
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Israel-Assis
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0002-8766-1041
    - icon: fontawesome/brands/github
      link: https://github.com/i-assis
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/i-assis
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/i-assis-77105257/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/assiz
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/lexfridman
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/feecunicamp/?hl=en


extra_css:
  - _styles/extra.css
  - _styles/hyperlink.css
  # - _styles/view-big-img.css

extra_javascript:
  # Math:  
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_CHTML" # 1st
  - _assets/js/mathjax.js # must be before mathjax
  - https://polyfill.io/v3/polyfill.min.js?features=es6 # suggested by Material for MkDocs
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js # suggested by Material for MkDocs
  # Mermaid:
  -  https://unpkg.com/browse/mermaid@8.8.0/
  -  _assets/js/mermaid.js
  # markdown-it:
  # - https://cdn.jsdelivr.net/npm/markdown-it-container@3.0.0/
  # Else:
  - _assets/js/view-bigimg.js
  - _assets/js/extra.js
  